### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by victorparragarcia** [zagortenay333/ciliora-tertia-shell#1]
Is there a matching GTK theme for this? I think that Gnome-Breeze (gtk port from default Plasma 5 theme) is amazing and is very close to your shell theme but I'm trying to modify yours throu the css file (like the blue highlights, the "cristal" borders that are a little bit out of place and so on) but nothing happens, should I do something else? :S

![captura de pantalla de 2015-06-06 22-20-36](https://cloud.githubusercontent.com/assets/12498399/8021312/8ad3de44-0c9a-11e5-8a99-7e4a29f342de.png)

**Comment by zagortenay333** [comment]
Not sure where the request here is?

I think [Arc](https://github.com/horst3180/Arc-theme) is the best fit for Tertia right now.

As for the css, did you restart the theme when you edited the css and images? Did you apply the root theme? You need to give more info than that.
