### ISSUE TITLE
Wrong icon size in Notifications Popop

### ISSUE THREAD

**Issue by SKUndef** [zagortenay333/ciliora-tertia-shell#13]
Hi,

thank you for your last commits, they work very well on hidpi screens. I have found a bug on too much big discard icon on Notifications Popup.

I think the attached image will clarify better ;-)

Thanks!

![notifications_popup_icon_bug](https://cloud.githubusercontent.com/assets/5783302/26442274/15b220e6-4134-11e7-8789-40f6950f0856.png)

**Comment by zagortenay333** [comment]
Gnome 3.24 doesn't have that close icon anymore.

**Comment by SKUndef** [comment]
I see, so i should checkout the https://github.com/zagortenay333/ciliora-tertia-shell/commit/eb783ac5b517581a2dac09a974011fb4ab48a301 commit for Gnome 3.22 release, but i would lose the font-size unit conversion to "em".

I think i will live with the slightly bigger icon until Fedora 26 :-D

Thanks again, closing the issue!

**Comment by zagortenay333** [comment]
You should have mentioned that you were still on 3.24. I usually don't bother maintaining older versions. Srry.

**Comment by SKUndef** [comment]
No problem, sorry for the lack of information ;-)

**Comment by zagortenay333** [comment]
If you're not too lazy to install sass, then it's pretty easy to fix the fonts since they are all in one module. Just tweak it and compile to css.
https://github.com/zagortenay333/ciliora-tertia-shell/blob/master/Ciliora-Tertia/gnome-shell/scss/base/_font.scss

**Comment by SKUndef** [comment]
Ok i will give it a shot!
