### ISSUE TITLE
GNOME 3.18 support

### ISSUE THREAD

**Issue by mydegeneration** [zagortenay333/ciliora-tertia-shell#4]
Hey, just wanted to let you know the theme for the most part looks fine on 3.18 except for a few instances.

![screenshot from 2015-10-06 09-50-19](https://cloud.githubusercontent.com/assets/7192681/10310572/996315ee-6c10-11e5-85ff-68bdc3ebe9c3.png)
![screenshot from 2015-10-06 09-55-14](https://cloud.githubusercontent.com/assets/7192681/10310573/9beb9b6a-6c10-11e5-8e6d-58536a524526.png)
![screenshot from 2015-10-06 09-55-37](https://cloud.githubusercontent.com/assets/7192681/10310577/9d8e0368-6c10-11e5-9229-7ba935cdfacd.png)

**Comment by zagortenay333** [comment]
Yeah, I  know. I'm waiting for f23 to get rpmfusion to install GS 3.18.

**Comment by mydegeneration** [comment]
I also noticed the app-loading animation square thingy on the top-panel gets distorted. I forgot what you call it.

**Comment by zagortenay333** [comment]
No worries, I already know all the change made for GS 3.18.

**Comment by mydegeneration** [comment]
BTW, I think you could get rpmfusion on 23 already by installing the "rawhide" version.

**Comment by zagortenay333** [comment]
Yeah, but last time I had lots of issues with rawhide.

**Comment by mydegeneration** [comment]
Ever thought of trying Arch or Antergos?

**Comment by zagortenay333** [comment]
Nah, I don't won't t bother with anything Arch.

**Comment by zagortenay333** [comment]
`3.18` is added now!
