### ISSUE TITLE
end-session-dialog separator too thick

### ISSUE THREAD

**Issue by mydegeneration** [zagortenay333/ciliora-tertia-shell#5]
Is the separator between Restart and Power Off supposed to be this thick?
![screenshot from 2015-11-08 11-32-23](https://cloud.githubusercontent.com/assets/7192681/11021356/dab86a92-860c-11e5-83e3-7dbd641fc2e1.png)

**Comment by zagortenay333** [comment]
Unfortunately, gnome-shell's css isn't advanced enough to deal with border collapsing that is needed in such a case.

I don't mind it that much to be honest.

**Comment by zagortenay333** [comment]
I'm gonna close since there is nothing I can do here.

**Comment by zagortenay333** [comment]
@mydegeneration, what do you say about this look for the dialog buttons:
![screenshot from 2015-11-10 13-30-15](https://cloud.githubusercontent.com/assets/11144630/11062454/65c2267a-87af-11e5-9599-664c2aab704b.png)

It would solve the double border. You can check it out on the `button-test` branch.

**Comment by zagortenay333** [comment]
Ok, I made the dialog buttons look like this. This looks pretty neat too.

**Comment by mydegeneration** [comment]
I kinda like them but I feel like the font on restart should be dark.
