### ISSUE TITLE
Athentication required dialog user space

### ISSUE THREAD

**Issue by mydegeneration** [zagortenay333/ciliora-tertia-shell#6]
![screenshot from 2015-11-08 11-37-54](https://cloud.githubusercontent.com/assets/7192681/11021372/5c08d280-860d-11e5-82a9-efc8f3171539.png)

**Comment by zagortenay333** [comment]
Is the blue background the issue?

**Comment by mydegeneration** [comment]
Yeah!

**Comment by zagortenay333** [comment]
Fixed with 9267b74a74590d7d7dcc8ad3ea826f9e4059eb3a
