### ISSUE TITLE
more padding for animated icon on panel

### ISSUE THREAD

**Issue by arshavindn** [zagortenay333/ciliora-tertia-shell#7]
I think it will be better if increase padding of animated icon on panel. Hope you take a look at it.

**Comment by zagortenay333** [comment]
I tried, but it can't be done as far as I see.

**Comment by zagortenay333** [comment]
Will look into it again.

**Comment by zagortenay333** [comment]
OK, this should be fixed with 040654c374a5c93a5ba3d20e3dca749b6ba81c5e
