### ISSUE TITLE
check icon on title right click menu padding

### ISSUE THREAD

**Issue by arshavindn** [zagortenay333/ciliora-tertia-shell#8]
Do you think that check icon needs padding to the left for better good-looking?
![unsaved document 1 - gedit_019](https://cloud.githubusercontent.com/assets/10246162/12530467/bd83ede2-c212-11e5-88b5-5dfd6017d7ad.png)

**Comment by zagortenay333** [comment]
It's problematic due to the `spacing` property. The only way to fix is to use an ugly fix involving margins.

I fixed it with c178d7e8dde54b20f77636dcb727f7613b6da65d. Hopefully there won't be any issues
