### ISSUE TITLE
Volume level indicator bug

### ISSUE THREAD

**Issue by mydegeneration** [zagortenay333/ciliora-tertia-shell#9]
Fedora 24, GNOME 3.20.2
![screenshot from 2016-10-09 22-12-35](https://cloud.githubusercontent.com/assets/7192681/19225607/828e22de-8e6d-11e6-84dc-646fad5c80ab.png)

**Comment by zagortenay333** [comment]
Ah, that happened when I updated to 3.22. I thought they were compatible.. I tagged the version 3.20: https://github.com/zagortenay333/ciliora-tertia-shell/releases
